permalink: /blog/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ["jekyll-paginate", "jekyll-gist"]

exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
highligher: rouge
paginate: 5
paginate_path: "/blog/page/:num/"
excerpt_separator: <!--more-->

title : Randy City
tagline: Site Tagline
author :
  name : Randy Lai
  email : randy3k.cs.lai@gmail.com
  github : randy3k
  # twitter : username
  # feedburner : feedname

url : http://randy.city

nav:
  - text: Profile
    url: /profile/
  - text: Research
    url: /research/
  - text: Stuffs
    url: /stuffs/
  - text: Blog
    url: /blog/

archive_path: /blog/archive/
categories_path : /blog/categories/
tags_path : /blog/tags/

disqus :
  short_name : randycity
