permalink: /blog/:year/:month/:day/:title
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->

title : RTalks.net
tagline: Site Tagline
author :
  name : Randy Lai
  email : randy3k.cs.lai@gmail.com
  github : randy3k
  # twitter : username
  # feedburner : feedname

url : http://rtalks.net

nav:
  - text: Research
    url: /research/
  - text: Apps
    url: /apps/
  - text: Blog
    url: /blog/

archive_path: /blog/archive/
categories_path : /categories/
tags_path : /tags/

disqus :
  short_name : randy3k
