# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: pretty
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
paginate: 2
paginate_path: "blog/page:num"

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : RTalks.net
tagline: Site Tagline
author :
  name : Randy Lai
  email : randy3k.cs.lai@gmail.com
  github : randy3k
  # twitter : username
  # feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://rtalks.net

nav:
  - text: Research
    url: /research/
  - text: Apps
    url: /apps/
  - text: Blog
    url: /blog/
  - text: Tags
    url: /tags/

# All Jekyll-Bootstrap specific configurations are namespaced into this hash

JB :
  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive/
  categories_path : /categories/
  tags_path : /tags/

  comments :
    provider : disqus
    disqus :
      short_name : randy3k
