permalink: /blog/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ["README.md", "Rakefile"]
highligher: rouge
paginate: 5
paginate_path: "/blog/page/:num/"
excerpt_separator: <!--more-->

title : RTalks.net
tagline: Site Tagline
author :
  name : Randy Lai
  email : randy3k.cs.lai@gmail.com
  github : randy3k
  # twitter : username
  # feedburner : feedname

url : http://rtalks.net

nav:
  - text: Profile
    url: /profile/
  - text: Research
    url: /research/
  - text: Software
    url: /software/
  - text: Blog
    url: /blog/

archive_path: /blog/archive/
categories_path : /blog/categories/
tags_path : /blog/tags/

disqus :
  short_name : randy3k
