mode: dev
permalink: /blog/:title/
markdown: kramdown
markdown_ext: foo
kramdown:
  input: GFM
  coderay_line_numbers: nil

exclude: ["README.md", "Rakefile", 'bootstrap', 'Rakefile',
          "Gemfile*", "rtalks.sublime-workspace", "rtalks.sublime-project"]
highligher: pygments
paginate: 5
paginate_path: "/blog/page/:num/"
excerpt_separator: <!--more-->

title : RTalks.net
tagline: Site Tagline
author :
  name : Randy Lai
  email : randy3k.cs.lai@gmail.com
  github : randy3k
  # twitter : username
  # feedburner : feedname

url : http://rtalks.net

nav:
  - text: Research
    url: /research/
  - text: Apps
    url: /apps/
  - text: Blog
    url: /blog/

archive_path: /blog/archive/
categories_path : /blog/categories/
tags_path : /blog/tags/

disqus :
  short_name : randy3k
